# Generated by Django 5.1.5 on 2025-01-22 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('session_id', models.CharField(max_length=100)),
                ('user_agent', models.TextField()),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '배너 인덱스',
                'verbose_name_plural': '배너 인덱스 목록',
            },
        ),
        migrations.CreateModel(
            name='BannerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('session_id', models.CharField(max_length=100)),
                ('user_agent', models.TextField()),
                ('is_bot', models.BooleanField(default=False)),
                ('clicked_image', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.bannerindex')),
            ],
            options={
                'verbose_name': '배너 클릭',
                'verbose_name_plural': '배너 클릭 목록',
            },
        ),
    ]
