# Generated by Django 5.1.5 on 2025-01-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbanner',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
